export const dynamic='force-dynamic';
import Link from 'next/link';import {api,money} from '../lib/api';
export default async function Home(){let projects:any[]=[];let stats:any={users:0,projects:0,investments:0,raisedAmount:0};try{[projects,stats]=await Promise.all([api('/projects'),api('/public/stats')])}catch{}
return <>
<header className="nav"><div className="container row"><Link href="/" className="brand"><span className="brand-mark">N</span><span>nova.com<small>INVESTISSEMENT • IMPACT • AVENIR</small></span></Link><nav className="navlinks"><Link href="/">Accueil</Link><Link href="/projects">Projets</Link><Link href="/about">À propos</Link><Link href="/faq">FAQ</Link><Link href="/login" className="btn outline">Se connecter</Link><Link href="/register" className="btn">Créer un compte</Link></nav></div></header>
<main>
<section className="hero-v5"><div className="hero-overlay"></div><div className="container hero-content"><div className="hero-copy"><span className="tag hero-tag">Immobilier • Énergie renouvelable</span><h1>Investissez dans un <em>avenir durable</em> et rentable</h1><p>Accédez à des projets immobiliers et d’énergies renouvelables sélectionnés et publiés directement par nova.com.</p><div className="hero-actions"><Link className="btn hero-primary" href="/projects">Découvrir les projets <span>→</span></Link><Link className="btn hero-secondary" href="/register">Créer mon compte</Link></div><div className="hero-benefits"><span>◉ <b>Sécurisé</b><small>Vos fonds suivis</small></span><span>ϟ <b>Rendement attractif</b><small>Des projets sélectionnés</small></span><span>♧ <b>Parrainage</b><small>Gagnez ensemble</small></span><span>◷ <b>Retraits simples</b><small>Depuis votre wallet</small></span></div></div><div className="hero-side"><div><b>Énergies renouvelables</b><small>Une énergie propre pour demain</small></div><div><b>Immobilier</b><small>Des infrastructures pour un meilleur cadre de vie</small></div></div></div></section>
<section className="stats"><div className="container stat-grid"><div><b>{Number(stats.users).toLocaleString('fr-FR')}</b><small>Utilisateurs inscrits</small></div><div><b>{Number(stats.investments).toLocaleString('fr-FR')}</b><small>Investissements</small></div><div><b>{money(stats.raisedAmount)}</b><small>Montant collecté</small></div><div><b>{Number(stats.projects).toLocaleString('fr-FR')}</b><small>Projets disponibles</small></div><div><b>24/7</b><small>Suivi de votre espace</small></div></div></section>
<section className="section"><div className="container"><div className="row"><div><h2>Projets disponibles</h2><p className="muted">Les projets sont publiés et gérés uniquement par le fondateur.</p></div><Link href="/projects">Tout voir →</Link></div><div className="grid">{projects.slice(0,6).map(p=><article className="card" key={p.id}>{p.coverUrl&&<img src={p.coverUrl} alt="" className="project-cover"/>}<span className="tag">{p.category}</span><h3>{p.title}</h3><p className="muted">{p.description?.slice(0,130)}…</p><div className="row"><b>{money(p.minInvestment)} min.</b><b>{Array.isArray(p.returnPlans)&&p.returnPlans[0]?.dailyProfit?money(p.returnPlans[0].dailyProfit)+'/j':Number(p.expectedReturnPct||0).toFixed(2)+'%'}</b></div><div className="progress" style={{margin:'15px 0 8px'}}><span style={{width:`${Math.min(100,Number(p.raisedAmount)/Number(p.targetAmount)*100)}%`}}/></div><Link href={'/projects/'+p.id} className="btn secondary">Détails</Link></article>)}</div></div></section>
</main><footer className="container footer"><div className="row"><span>nova.com — plateforme d’investissement immobilier et énergies renouvelables.</span><span><Link href="/about">À propos</Link> · <Link href="/faq">FAQ</Link> · <Link href="/support">Support</Link> · <Link href="/terms">Conditions</Link> · <Link href="/privacy">Confidentialité</Link></span></div></footer></>}
