import {Injectable,ForbiddenException,NotFoundException}from'@nestjs/common';import {PrismaService}from'./prisma.service';
@Injectable()export class ProjectsService{constructor(private p:PrismaService){}list(){return this.p.project.findMany({where:{status:{in:['PUBLISHED','FUNDING','FUNDED','ACTIVE','PAUSED','COMPLETED']}},orderBy:{createdAt:'desc'}})}get(id:string){return this.p.project.findUnique({where:{id},include:{updates:{orderBy:{createdAt:'desc'}},_count:{select:{investments:true}}}})}private admin(u:any){if(u?.role!=='SUPER_ADMIN')throw new ForbiddenException('Fondateur uniquement')}
create(u:any,d:any){this.admin(u);return this.p.project.create({data:{title:d.title,slug:d.slug,category:d.category||'REAL_ESTATE',description:d.description,coverUrl:d.coverUrl||d.imageUrl,galleryUrls:d.galleryUrls||[],targetAmount:d.targetAmount,minInvestment:d.minInvestment||100,expectedReturnPct:17,returnPlans:[],durationDays:d.durationDays,startsAt:d.startsAt?new Date(d.startsAt):undefined,endsAt:d.endsAt?new Date(d.endsAt):undefined}})}
update(u:any,id:string,d:any){this.admin(u);const data:any={};for(const k of ['title','slug','category','description','coverUrl','galleryUrls','targetAmount','minInvestment','durationDays'])if(d[k]!==undefined)data[k]=d[k]; data.expectedReturnPct=17; data.returnPlans=[];for(const k of ['startsAt','endsAt'])if(d[k]!==undefined)data[k]=d[k]?new Date(d[k]):null;return this.p.project.update({where:{id},data})}
async publish(u:any,id:string){this.admin(u);const project=await this.p.project.findUnique({where:{id}});if(!project)throw new NotFoundException('Projet introuvable');const startsAt=new Date();const endsAt=new Date(startsAt.getTime()+Number(project.durationDays)*86400000);return this.p.project.update({where:{id},data:{status:'FUNDING',publishedAt:startsAt,startsAt,endsAt}})}
setStatus(u:any,id:string,status:any){this.admin(u);if(!['DRAFT','PUBLISHED','FUNDING','FUNDED','ACTIVE','PAUSED','COMPLETED'].includes(status))throw new Error('Statut invalide');return this.p.project.update({where:{id},data:{status}})}
remove(u:any,id:string){this.admin(u);return this.p.project.delete({where:{id}})}
async addUpdate(u:any,id:string,title:string,content:string){this.admin(u);if(!await this.p.project.findUnique({where:{id}}))throw new NotFoundException('Projet introuvable');return this.p.projectUpdate.create({data:{projectId:id,title,content}})}
}
